// <auto-generated />
using System;
using HyperLocalMarket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyperLocalMarket.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724234419_AddStoreSetupFields")]
    partial class AddStoreSetupFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HyperLocalMarket.Domain.Stores.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("DeliveryRadiusKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsAcceptingOrders")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeliveryAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPickupAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Stores_Status");

                    b.HasIndex("Status", "IsAcceptingOrders")
                        .HasDatabaseName("IX_Stores_Status_IsAcceptingOrders");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Stores_UserId_Status");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "RetryCount");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Stores.Store", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("HyperLocalMarket.Domain.Stores.StoreBusinessHour", "BusinessHours", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid")
                                .HasColumnName("StoreId");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<TimeOnly?>("ClosesAt")
                                .HasColumnType("time without time zone")
                                .HasColumnName("ClosesAt");

                            b1.Property<string>("DayOfWeek")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DayOfWeek");

                            b1.Property<bool>("IsOpen24Hours")
                                .HasColumnType("boolean")
                                .HasColumnName("IsOpen24Hours");

                            b1.Property<TimeOnly?>("OpensAt")
                                .HasColumnType("time without time zone")
                                .HasColumnName("OpensAt");

                            b1.HasKey("StoreId", "Id");

                            b1.ToTable("StoreBusinessHours", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("HyperLocalMarket.Domain.ValueObjects.StoreLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("CountryCode");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.AdminArea", "AdminArea", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Level1")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel1");

                                    b2.Property<int?>("Level1Id")
                                        .HasMaxLength(100)
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel1Id");

                                    b2.Property<string>("Level2")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel2");

                                    b2.Property<int?>("Level2Id")
                                        .HasMaxLength(100)
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel2Id");

                                    b2.Property<string>("Level3")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel3");

                                    b2.Property<int?>("Level3Id")
                                        .HasMaxLength(100)
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel3Id");

                                    b2.Property<string>("Level4")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel4");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.GeoLocation", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Longitude");

                                    b2.Property<Point>("Point")
                                        .IsRequired()
                                        .HasColumnType("geography (point, 4326)")
                                        .HasColumnName("Location");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.HasIndex("Point")
                                        .HasDatabaseName("IX_Stores_Location_Point");

                                    NpgsqlIndexBuilderExtensions.HasMethod(b2.HasIndex("Point"), "gist");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.PostalAddress", "Address", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AddressLine1")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("AddressLine1");

                                    b2.Property<string>("AddressLine2")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("AddressLine2");

                                    b2.Property<string>("Landmark")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("Landmark");

                                    b2.Property<string>("Locality")
                                        .HasMaxLength(150)
                                        .HasColumnType("character varying(150)")
                                        .HasColumnName("Locality");

                                    b2.Property<string>("Postcode")
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("Postcode");

                                    b2.Property<string>("Region")
                                        .HasMaxLength(150)
                                        .HasColumnType("character varying(150)")
                                        .HasColumnName("Region");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.HasIndex("Locality")
                                        .HasDatabaseName("IX_Stores_Locality");

                                    b2.HasIndex("Region")
                                        .HasDatabaseName("IX_Stores_Region");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("AdminArea")
                                .IsRequired();

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.Navigation("BusinessHours");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.Session", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Users.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
