// <auto-generated />
using System;
using HyperLocalMarket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyperLocalMarket.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115013157_PointPostGisInStoreTableUpdate")]
    partial class PointPostGisInStoreTableUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HyperLocalMarket.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Entities.Store", b =>
                {
                    b.OwnsOne("HyperLocalMarket.Domain.ValueObjects.StoreLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("CountryCode");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.AdminArea", "AdminArea", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Level1")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel1");

                                    b2.Property<int?>("Level1Id")
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel1Id");

                                    b2.Property<string>("Level2")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel2");

                                    b2.Property<int?>("Level2Id")
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel2Id");

                                    b2.Property<string>("Level3")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel3");

                                    b2.Property<int?>("Level3Id")
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel3Id");

                                    b2.Property<string>("Level4")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel4");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.GeoLocation", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Longitude");

                                    b2.Property<Point>("Point")
                                        .HasColumnType("geography (point, 4326)")
                                        .HasColumnName("Location");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.PostalAddress", "Address", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AddressLine1")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AddressLine1");

                                    b2.Property<string>("AddressLine2")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AddressLine2");

                                    b2.Property<string>("Landmark")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("Landmark");

                                    b2.Property<string>("Locality")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("Locality");

                                    b2.Property<string>("Postcode")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("Postcode");

                                    b2.Property<string>("Region")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("Region");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("AdminArea")
                                .IsRequired();

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
