// <auto-generated />
using System;
using HyperLocalMarket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyperLocalMarket.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HyperLocalMarket.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Categories.CategoryAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryAlias");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Categories.CategoryProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProposedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SuggestedParentCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ResolvedCategoryId");

                    b.HasIndex("SuggestedParentCategoryId");

                    b.HasIndex("ProductId", "Status")
                        .HasDatabaseName("IX_CategoryProposals_ProductId_Status");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_CategoryProposals_Status_CreatedAtUtc");

                    b.HasIndex("StoreId", "Status")
                        .HasDatabaseName("IX_CategoryProposals_StoreId_Status");

                    b.ToTable("CategoryProposals", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CategoryAssignmentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProposalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_CategoryProposalId")
                        .HasFilter("\"CategoryProposalId\" IS NOT NULL");

                    b.HasIndex("CategoryId", "Status")
                        .HasDatabaseName("IX_Products_CategoryId_Status");

                    b.HasIndex("StoreId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_StoreId_Name");

                    b.HasIndex("StoreId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_StoreId_Slug");

                    b.HasIndex("StoreId", "Status")
                        .HasDatabaseName("IX_Products_StoreId_Status");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductImages_PrimaryProductImage")
                        .HasFilter("\"IsPrimary\" = TRUE AND \"ProductVariantId\" IS NULL");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ProductId", "DisplayOrder")
                        .HasDatabaseName("IX_ProductImages_ProductId_DisplayOrder");

                    b.HasIndex("ProductId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductImages_PrimaryVariantImage")
                        .HasFilter("\"IsPrimary\" = TRUE AND \"ProductVariantId\" IS NOT NULL");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "DisplayOrder")
                        .HasDatabaseName("IX_ProductOptions_ProductId_DisplayOrder");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductOptions_ProductId_Name");

                    b.ToTable("ProductOptions", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionId");

                    b.ToTable("ProductOptionValue");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityIncrement")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("SalesUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductVariants_DefaultPerProduct")
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("ProductId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductVariants_ProductId_Barcode")
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex("ProductId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductVariants_ProductId_Sku")
                        .HasFilter("\"Sku\" IS NOT NULL");

                    b.HasIndex("ProductId", "Status")
                        .HasDatabaseName("IX_ProductVariants_ProductId_Status");

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductVariantSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductOptionValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionId");

                    b.HasIndex("ProductOptionValueId");

                    b.HasIndex("ProductVariantId", "ProductOptionId")
                        .IsUnique()
                        .HasDatabaseName("UX_VariantSelections_VariantId_OptionId");

                    b.ToTable("ProductVariantSelections", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Stores.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("DeliveryRadiusKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsAcceptingOrders")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeliveryAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPickupAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Stores_Status");

                    b.HasIndex("Status", "IsAcceptingOrders")
                        .HasDatabaseName("IX_Stores_Status_IsAcceptingOrders");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Stores_UserId_Status");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "RetryCount");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Categories.CategoryAlias", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Categories.Category", null)
                        .WithMany("Aliases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Categories.CategoryProposal", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperLocalMarket.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperLocalMarket.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ResolvedCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HyperLocalMarket.Domain.Stores.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperLocalMarket.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("SuggestedParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.Product", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HyperLocalMarket.Domain.Categories.CategoryProposal", null)
                        .WithOne()
                        .HasForeignKey("HyperLocalMarket.Domain.Products.Product", "CategoryProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HyperLocalMarket.Domain.Stores.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductImage", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Products.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperLocalMarket.Domain.Products.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductOption", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Products.Product", null)
                        .WithMany("Options")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductOptionValue", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Products.ProductOption", null)
                        .WithMany("Values")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HyperLocalMarket.Domain.Products.Dimensions", "ShippingDimensions", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Height")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("ShippingHeight");

                            b1.Property<decimal>("Length")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("ShippingLength");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ShippingDimensionUnit");

                            b1.Property<decimal>("Width")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("ShippingWidth");

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("ProductVariants");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.OwnsOne("HyperLocalMarket.Domain.Products.Money", "CompareAtPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CompareAtPriceAmount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("CompareAtPriceCurrencyCode")
                                .IsFixedLength();

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("ProductVariants");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.OwnsOne("HyperLocalMarket.Domain.Products.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("PriceCurrencyCode")
                                .IsFixedLength();

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("ProductVariants");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.OwnsOne("HyperLocalMarket.Domain.Products.Weight", "ShippingWeight", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ShippingWeightUnit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("ShippingWeightValue");

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("ProductVariants");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.Navigation("CompareAtPrice");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("ShippingDimensions");

                    b.Navigation("ShippingWeight");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductVariantSelection", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Products.ProductOption", null)
                        .WithMany()
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperLocalMarket.Domain.Products.ProductOptionValue", null)
                        .WithMany()
                        .HasForeignKey("ProductOptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperLocalMarket.Domain.Products.ProductVariant", null)
                        .WithMany("Selections")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Stores.Store", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("HyperLocalMarket.Domain.Stores.StoreBusinessHour", "BusinessHours", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid")
                                .HasColumnName("StoreId");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<TimeOnly?>("ClosesAt")
                                .HasColumnType("time without time zone")
                                .HasColumnName("ClosesAt");

                            b1.Property<string>("DayOfWeek")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DayOfWeek");

                            b1.Property<bool>("IsOpen24Hours")
                                .HasColumnType("boolean")
                                .HasColumnName("IsOpen24Hours");

                            b1.Property<TimeOnly?>("OpensAt")
                                .HasColumnType("time without time zone")
                                .HasColumnName("OpensAt");

                            b1.HasKey("StoreId", "Id");

                            b1.ToTable("StoreBusinessHours", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("HyperLocalMarket.Domain.ValueObjects.StoreLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("CountryCode");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.AdminArea", "AdminArea", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Level1")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel1");

                                    b2.Property<int?>("Level1Id")
                                        .HasMaxLength(100)
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel1Id");

                                    b2.Property<string>("Level2")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel2");

                                    b2.Property<int?>("Level2Id")
                                        .HasMaxLength(100)
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel2Id");

                                    b2.Property<string>("Level3")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel3");

                                    b2.Property<int?>("Level3Id")
                                        .HasMaxLength(100)
                                        .HasColumnType("integer")
                                        .HasColumnName("AdminLevel3Id");

                                    b2.Property<string>("Level4")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("AdminLevel4");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.GeoLocation", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Longitude");

                                    b2.Property<Point>("Point")
                                        .IsRequired()
                                        .HasColumnType("geography (point, 4326)")
                                        .HasColumnName("Location");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.HasIndex("Point")
                                        .HasDatabaseName("IX_Stores_Location_Point");

                                    NpgsqlIndexBuilderExtensions.HasMethod(b2.HasIndex("Point"), "gist");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.OwnsOne("HyperLocalMarket.Domain.ValueObjects.PostalAddress", "Address", b2 =>
                                {
                                    b2.Property<Guid>("StoreLocationStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AddressLine1")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("AddressLine1");

                                    b2.Property<string>("AddressLine2")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("AddressLine2");

                                    b2.Property<string>("Landmark")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("Landmark");

                                    b2.Property<string>("Locality")
                                        .HasMaxLength(150)
                                        .HasColumnType("character varying(150)")
                                        .HasColumnName("Locality");

                                    b2.Property<string>("Postcode")
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("Postcode");

                                    b2.Property<string>("Region")
                                        .HasMaxLength(150)
                                        .HasColumnType("character varying(150)")
                                        .HasColumnName("Region");

                                    b2.HasKey("StoreLocationStoreId");

                                    b2.HasIndex("Locality")
                                        .HasDatabaseName("IX_Stores_Locality");

                                    b2.HasIndex("Region")
                                        .HasDatabaseName("IX_Stores_Region");

                                    b2.ToTable("Stores");

                                    b2.WithOwner()
                                        .HasForeignKey("StoreLocationStoreId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("AdminArea")
                                .IsRequired();

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.Navigation("BusinessHours");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.Session", b =>
                {
                    b.HasOne("HyperLocalMarket.Domain.Users.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Categories.Category", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Options");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductOption", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Products.ProductVariant", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("HyperLocalMarket.Domain.Users.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
